// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTP9mIeN2qWUYSFlVtcRrIAiNxYs8EORQ',
    appId: '1:15918805445:web:eed09421aee5d6fd709bac',
    messagingSenderId: '15918805445',
    projectId: 'officialpbl',
    authDomain: 'officialpbl.firebaseapp.com',
    storageBucket: 'officialpbl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLtSTQJAjmcnocSRhwm6XtjilJ5UoiK4g',
    appId: '1:15918805445:android:bfa12715e8c9fa55709bac',
    messagingSenderId: '15918805445',
    projectId: 'officialpbl',
    storageBucket: 'officialpbl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QN98pYZV8TOq_EQqBJqEcLakYXGMLts',
    appId: '1:15918805445:ios:3305638f83a2de7a709bac',
    messagingSenderId: '15918805445',
    projectId: 'officialpbl',
    storageBucket: 'officialpbl.appspot.com',
    iosBundleId: 'com.example.officialPbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2QN98pYZV8TOq_EQqBJqEcLakYXGMLts',
    appId: '1:15918805445:ios:3305638f83a2de7a709bac',
    messagingSenderId: '15918805445',
    projectId: 'officialpbl',
    storageBucket: 'officialpbl.appspot.com',
    iosBundleId: 'com.example.officialPbl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTP9mIeN2qWUYSFlVtcRrIAiNxYs8EORQ',
    appId: '1:15918805445:web:17954300221e2215709bac',
    messagingSenderId: '15918805445',
    projectId: 'officialpbl',
    authDomain: 'officialpbl.firebaseapp.com',
    storageBucket: 'officialpbl.appspot.com',
  );
}
